api_key: "cfa7d3a989a0494d89722f36fc4f4400"
files:
  audio_file: "/home/huy/pipe/transcribe_and_detect_speech/assets/audio/audio.mp3"
  video_file: "/home/huy/pipe/transcribe_and_detect_speech/assets/video/video.mp4"